variable ami {}
variable instance_type {}
variable region {}
variable cidr_block_vpc {}
variable instance_tenancy {}
variable prefix {}
variable cidr_block_public_subnet {}
variable cidr_block_private_subnet1 {}
variable cidr_block_private_subnet2 {}
variable cidr_block_route {}
variable key_name {}
variable ssh_key_path {}
variable subnetgroup {}
variable allocated_storage {}
variable engine {}           
variable engine_version {}        
variable instance_class {}      
variable multi_az {}             
variable name {}             
variable username {}             
# password              = random_password.password.result
variable password {}                
variable port {}                
variable publicly_accessible {}
variable storage_encrypted {}  
variable storage_type {}     
variable security_group_ec2 {}
variable "rds_port" {}
variable security_group_db {}
